codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false

coverage:
  precision: 2
  round: down
  range: "50...90"
  status:
    project:
      default:
        target: auto
        threshold: 5%
        base: auto
    patch:
      default:
        target: auto
        threshold: 10%
        base: auto

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: false