blank_issues_enabled: false
contact_links:
  - name: VS Code Paste Image Discussions
    url: https://github.com/kjon-life/vscode-paste-image/discussions
    about: Please ask and answer questions here.
  - name: VS Code Paste Image Documentation
    url: https://github.com/kjon-life/vscode-paste-image#readme
    about: Please check the documentation before opening an issue.